[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  targetPort = 5173   # Vite's dev port
  port = 8888         # Netlify Dev proxy port

  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200